<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SinfoniaStudio.DiscordLogExporter</RootNamespace>
    <AssemblyName>DiscordLogExporter</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\SinfoniaOperator.Core\SinfoniaOperator.Core.csproj"
      SetTargetFramework="TargetFramework=net10.0"
      SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>

</Project>
